### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by eccoilmoro** [danvk/oldnyc#108]
Hi, I'm tryng to install oldnyc on my ubuntu server 15. I cannot create the virtualenv due to an error I don't understand. The command sequnce I executed is :
git clone git://github.com/danvk/oldnyc.git
cd oldnyc
virtualenv env --python=python3     
source env/bin/activate
pip3 install -r requirements.txt

![2016-03-25_182952](https://cloud.githubusercontent.com/assets/3404161/14049826/0a615cd2-f2b8-11e5-8d07-73f3f7a6bafc.png)

**Comment by danvk** [comment]
OldNYC uses Python 2, not Python 3.
