### ISSUE TITLE
Replace some Ocropus OCR with GPT OCR

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#145]
Had GPT existed in 2015, it would have been a much better choice than Ocropus. Alas!

Replacing Ocropus OCR with GPT OCR is essentially always a win. But OldNYC's users have provided an enormous number of corrections to the Ocropus OCR over the years. In that case, it's not a clear win.

Some stats:

- 28,160 images have Ocropus OCR
- 16,811 images have corrections
- 7,405 images have multiple corrections
- 11,349 images have no corrections

The images with no corrections tend to be ones that aren't displayed on the site. But some images that have received at least one edit are still pretty bad, e.g. [707823f-a](https://www.oldnyc.org/ocr.html#707823f-a):

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/8f1e3cc8-df62-408f-8d37-cb4bc07897c1">

The task here is to find some heuristic for deciding when it makes sense to replace the existing OCR with GPT.

**Comment by riordan** [comment]
Don't knock it; OCRopus was the best we had back then.
