### ISSUE TITLE
Stuytown is missing

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#22]
Stuytown & Peter Cooper Village are conspicuously devoid of markers:
![screen shot 2014-09-16 at 3 41 27 pm](https://cloud.githubusercontent.com/assets/98301/4293800/89c3c5b8-3dd9-11e4-9eaa-25bfcd6bb27f.png)

Surely there are images in these locations. But they're at cross-streets that no longer exist. This is a situation where the Google Maps geocoder is clearly an anachronism.

Possible solutions would be hand-coding this area, or building a "pure grid" geocoder for Manhattan which extends the existing grid.

**Comment by danvk** [comment]
Many of the Stuytown images _are_ in OldNYC, it's just that they have inaccurate geocodes, e.g. http://www.oldnyc.org/#711316f-a says "15th Street (East) and Avenue A" but is geocoded to 15th and 5th.

**Comment by riordan** [comment]
What if we just clustered these and did them manually?

**Comment by danvk** [comment]
I think that's the right approach. Has anyone made a big list of coordinates / formulas for the Manhattan grid?

Nice to see you're lurking @riordan :)

**Comment by riordan** [comment]
Missed ya buddy.

Are these ones where the geocode fails (group 1) or where we know there are more things getting geocodes that shouldn't?

If it's the former, it's a lot easier to break apart.


On 12/17/15 11:28, Dan Vanderkam wrote:
> I think that's the right approach. Has anyone made a big list of
> coordinates / formulas for the Manhattan grid?
>
> Nice to see you're lurking @riordan <https://github.com/riordan> :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danvk/oldnyc/issues/22#issuecomment-165501348>.
>

-- 
-- <br />
David Riordan <br />
david.riordan@gmail.com | gpg 235D 9DC9 5EF6 277C <br />
@riordan | +1 (203)-521-1222 <br />

**Comment by danvk** [comment]
I noticed that Google Maps API results include `"partial_match": true` when they're wrong, so those should be easy to filter out.

**Comment by danvk** [comment]
Hoping to get this out soon. There are some great new photos in this update.
![screen shot 2015-12-21 at 1 59 24 pm](https://cloud.githubusercontent.com/assets/98301/11939092/9185874e-a7ed-11e5-9ee2-5b75cb0c3dcf.png)

**Comment by danvk** [comment]
Handy commands for doing before/after shots:

    (c = map.getCenter(), {lat: c.lat(), lng: c.lng()})
    map.getZoom()

and then 

    map.setCenter(...);
    map.setZoom(...);
