### ISSUE TITLE
Re-style item view

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#42]
It currently looks cobbled together, especially on larger screens.

![screen shot 2015-03-31 at 2 08 37 pm](https://cloud.githubusercontent.com/assets/98301/6925758/a97c9662-d7af-11e4-824d-d0b304f782f5.png)

**Comment by danvk** [comment]
@mgiraldo any ideas around this?

The bits of information currently there are:

- Image title ("Manhattan: 42nd Street (West) - 5th Avenue")
- Rotate 90°
- Feedback
- OCR'd text (where available)
- Link to the back of the image (where available)
- Link to this photo
- Tweet
- Like
- Facebook Share
- Facebook Comment

**Comment by mgiraldo** [comment]
I do but implementing them required messing around a lot with the JavaScript and I didn't want to damage anything. I could do a PNG mockup if that works?

- mga

**Comment by danvk** [comment]
That would be great!

**Comment by mgiraldo** [comment]
does this help?
it is mostly spacing stuff and text hierarchy

![oldnyc-detail](https://cloud.githubusercontent.com/assets/133020/7399279/a814efb0-ee82-11e4-95ba-857981ed2dc5.png)

![rotate](https://cloud.githubusercontent.com/assets/133020/7399297/c76af9e0-ee82-11e4-958c-44663329c9fc.png)

the clipboard icon comes from [octicons](https://octicons.github.com/)
the text block width could also be % based but have a min-width of ~300px

**Comment by danvk** [comment]
Thanks, it does!

I'm a bit hesitant to put the rotate button on top of the photo like that. Most of the time it will be in the way & a distraction. It's just that for a smallish number (~10%) of photos, it's really helpful to have.

**Comment by mgiraldo** [comment]
![rotate](https://cloud.githubusercontent.com/assets/133020/7400294/cd908342-ee89-11e4-9659-c5ef5650e881.png)

**Comment by danvk** [comment]
Maybe the best solution is to show it on the bottom right. Then it will use any extra space available on either the bottom or the right, depending on the size of the image and the viewport.

Wide image:
![screen shot 2015-04-29 at 4 49 59 pm](https://cloud.githubusercontent.com/assets/98301/7401205/46aa8f74-ee90-11e4-8bd5-69fdf16c6ae4.png)

Tall image:
![screen shot 2015-04-29 at 4 49 45 pm](https://cloud.githubusercontent.com/assets/98301/7401206/46aae992-ee90-11e4-804f-7602b3d9b22e.png)

**Comment by mgiraldo** [comment]
top right better?

this way it is immediately accesible not requiring a scroll 

----- Original Message -----
