### ISSUE TITLE
Link to back of photo should go to NYPL digital collections page

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#43]

**Comment by danvk** [comment]
@riordan I think you were going to get me a big photo ID→digital collections ID mapping for this?

**Comment by riordan** [comment]
Yeah; may require a code change on our end. Let me verify.

**Comment by riordan** [comment]
I now have access to the db where we can directly get those updated URLs.

Should I just update them inside the `photos.pickle`?

**Comment by danvk** [comment]
Just commit a JSON file with the mapping. I'll incorporate it into
generate_static_site.py.

**Comment by danvk** [comment]
@riordan is there a pattern to the foreground/background UUIDs?

```
fg: 510d47dd-0618-a3d9-e040-e00a18064a99
bg: 510d47dd-0617-a3d9-e040-e00a18064a99
```

```
fg: 510d47dc-e46c-a3d9-e040-e00a18064a99
bg: 510d47dc-e46b-a3d9-e040-e00a18064a99
```

In both cases, going from foreground→background involves subtracting 1 from the 12th digit.

**Comment by riordan** [comment]
Haven't been able to discern one yet.
