### ISSUE TITLE
Migrate images to production S3 bucket

### ISSUE THREAD

**Issue by riordan** [danvk/oldnyc#51]
Migrate from development S3 to NYPL production S3 bucket

**Comment by riordan** [comment]
@danvk May need some help connecting our Amazon accounts. While I can `ls` and download everything using Cyberduck, I can't get the aws cli to read s3://images.oldnyc.org.

**Comment by danvk** [comment]
Do you have the copies from the hard drive you lent me a while back? It's just those files.

If not, I can email you my credentials.

```
$ s3cmd ls s3://images.oldnyc.org/
                       DIR   s3://images.oldnyc.org/600px/
                       DIR   s3://images.oldnyc.org/thumb/

$ s3cmd ls s3://images.oldnyc.org/600px/
  (slow; 50,000+ files!)
```

**Comment by danvk** [comment]
By "slow" I mean that it took ~6 minutes to run.

**Comment by riordan** [comment]
Yeah; that drive disappeared many moons ago :crying_cat_face:.

I'd been using `aws cli`, but now looking at s3cmd which seems to be doing the trick. Will let you know later today.
