### ISSUE TITLE
Publish all data as JSON

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#69]
OldSF had a `photos.json.gz` download which contained all the information about all the photos. OldNYC should have something similar. It should include image metadata, lat/lon and OCR text.

It should also include information about image crop boxes.

**Comment by denisnazarov** [comment]
Hey, wondering if its still possible to get this dump!

**Comment by danvk** [comment]
https://github.com/oldnyc/oldnyc.github.io/blob/master/data.json
