### ISSUE TITLE
Breaks with ad blocker

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#72]
@mgiraldo says that disconnect.me prevents the details page from loading.

The solution here might be to do #32, so that I can drop xdomain and do same-domain XHRs for data.

If I take this route, I'd like to do it ASAP so that I'm not mucking with DNS post-launch (DNS changes terrify me).

**Comment by danvk** [comment]
@mgiraldo if you feel strongly about this, it would help to get some more specifics, e.g. does removing the facebook comment widget make the issue go away?

**Comment by mgiraldo** [comment]
it works fine in my local instance following the instructions in the README:

![old nyc - photo 708788f-a](https://cloud.githubusercontent.com/assets/133020/7613449/c59b8cf6-f95e-11e4-8373-f04e5f1ab92c.png)

i just see it in the hosted version

**Comment by mgiraldo** [comment]
`ReferenceError: FB is not defined` in the hosted version

![inspector - http___www oldnyc org_ 708760f-a](https://cloud.githubusercontent.com/assets/133020/7613579/7ad8ebae-f95f-11e4-9b3d-6d9d232b52de.png)

**Comment by mgiraldo** [comment]
what if we use Disqus or some other non-FB alternative? i know we discussed this as an option

**Comment by danvk** [comment]
Is it blocking the FaceBook JavaScript bundle? If I open oldnyc.org in Chrome, go to the devtools and type `FB`, I get an object back. The error you posted would imply that this isn't happening.

**Comment by mgiraldo** [comment]
correct

**Comment by danvk** [comment]
This is a bug with disconnect.me then, not with OldNYC. I imagine if you went to facebook.com, nothing would load at all!

**Comment by mgiraldo** [comment]
ok... i wanted to see if we could avoid FB altogether

it's ok if you want to make it a requirement

**Comment by mgiraldo** [comment]
FWIW, it does work locally:

![inspector - http___localhost_5000_ 708760f-a](https://cloud.githubusercontent.com/assets/133020/7634381/9434a272-fa28-11e4-91ab-1eaeaa385a36.png)

your call anyway

**Comment by danvk** [comment]
Yeah, I don't know why your adblocker would block the facebook JS in one case but not the other.
