### ISSUE TITLE
right-clicking on map should not zoom out

### ISSUE THREAD

**Issue by mgiraldo** [danvk/oldnyc#77]

**Comment by danvk** [comment]
Which browser? I'm not seeing this behavior on Chrome.

**Comment by mgiraldo** [comment]
Firefox 38.0.1
Safari 8.0.6 (on double right click)

**Comment by danvk** [comment]
This happens in the Google Maps API demo, too: 
https://developers.google.com/maps/documentation/javascript/examples/map-simple

It's strange behavior, but it's not my bug!

**Comment by mgiraldo** [comment]
somebody thought right-click-to-zoom-out was a good idea

**Comment by danvk** [comment]
just not in chrome, apparently!
