### ISSUE TITLE
some items have no description, even though they do have in DC

### ISSUE THREAD

**Issue by mgiraldo** [danvk/oldnyc#78]
see: http://www.oldnyc.org/#711945f-a
and: http://digitalcollections.nypl.org/items/510d47dc-fdf7-a3d9-e040-e00a18064a99

among many others

**Comment by danvk** [comment]
I dropped the image description when it was just cross-streets. You can already get them from the map (and presumably you just clicked on the location), so they're redundant & in very large type.

**Comment by mgiraldo** [comment]
we would like them there if that's ok with you. we do not mind that redundancy

**Comment by danvk** [comment]
It's a pretty big waste of space, especially on small screens.

As an alternative, I could include the location text above the image grid, where it would be shared between all images.

Or under the map in the left gutter.

**Comment by mgiraldo** [comment]
if you prefer to do that... as long as there is some title text applicable to the photos... and as long as "1945" or "No Date" doesn't look like the title of the photo

**Comment by danvk** [comment]
Closing in favor of #82.
