### ISSUE TITLE
show nothing if an item has no date

### ISSUE THREAD

**Issue by mgiraldo** [danvk/oldnyc#79]
if an item has no date, show nothing (instead of "No Date")

if an item does have a date, show: "Description, Date"

related: #78

**Comment by danvk** [comment]
What's wrong with "No date"?

The title is currently "Description - Date" if there's an interesting description, so otherwise this is WAI.

**Comment by mgiraldo** [comment]
since there is no description, "1945" on its own is not understandable... "No date" on its own is also no clear... "Street scene 42nd & 5th ave" or "Street scene 42nd & 5th ave, 1945" is best in both cases in our opinion

**Comment by danvk** [comment]
"1945" and "No Date" are both pretty clear :)

If the description is "Street scene", it will be shown. The only titles that are suppressed are pure cross streets, e.g. "Manhattan: 42nd and 5th Ave"

**Comment by mgiraldo** [comment]
we really do not mind that redundancy... it does not look redundant right now (for us) because when you click an image/point you forget what you had clicked on and then the text (eg "42nd Street btwn 5 & 6 av")  gives you context.

**Comment by danvk** [comment]
I'm fine putting the text back in the top area, which is currently blank. I don't want to put it back in the image details area, which is already way too crowded.

**Comment by mgiraldo** [comment]
sure... i dont really know what the "top area" is but as long as there is that text...

**Comment by danvk** [comment]
Closing in favor of #82.
