### ISSUE TITLE
Indicate current location on the image details page

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#82]
I removed the redundant "Manhattan: Park Avenue - 39th Street" text to save space in the details panel. But it is still useful to see somewhere, particularly if you come to Old NYC via a link.

Two good locations would be on the top or on the side, under the map:
![image location](https://cloud.githubusercontent.com/assets/98301/7671186/eb7acefc-fc90-11e4-9636-f7327a1bf520.png)

I slightly prefer under the map since it's logically grouped with the map (it indicates location) and it would allow #56 to be implemented.

**Comment by danvk** [comment]
Here's what the two options look like:

![location-top](https://cloud.githubusercontent.com/assets/98301/7671227/c9f0d8e2-fc92-11e4-8beb-783c45d67846.png)
![location-left](https://cloud.githubusercontent.com/assets/98301/7671226/c9eefa04-fc92-11e4-8186-d60ba4a8f5a7.png)

Top:

```css
    position: fixed;
    top: 23px;
    left: 185px;
    color: white;
    font-size: 1.8em;
```

Left:

```css

    position: fixed;
    top: 210px;
    left: 13px;
    color: white;
    font-size: 1.8em;
    width: 150px;
```

**Comment by mgiraldo** [comment]
left looks better to me
