### ISSUE TITLE
Host over https

### ISSUE THREAD

**Issue by danvk** [danvk/oldnyc#88]
GitHub pages supports it. CloudFlare supports it.

Loading oldnyc-assets.nypl.org over https is less clear. @riordan do you guys have a secure endpoint for the images?

**Comment by danvk** [comment]
I set up `images.oldnyc.org` to be an alias for `oldnyc-assets.nypl.org` using CloudFlare. If it's added as a valid CNAME for `oldnyc-assets.nypl.org`, then https might just work.

Sample URL: http://images.oldnyc.org/600px/708760f-a.jpg

**Comment by riordan** [comment]
Did you just CDN a CDN, Dan?

sorry I didn't respond to this way back when.

Can't get the CNAME added now, but @mgiraldo or @hadro might be able to get it taken care of. That would require getting Brett to add it as a CNAME. Other option is to just serve it from the Cloudfront distribution URL, which shouldn't be hard for someone in the labs team to track down.

**Comment by mgiraldo** [comment]
this should be happening now... some propagation might be taking place

**Comment by mgiraldo** [comment]
looking at things here and it seems that the links broke... i will make the change locally in aws

**Comment by mgiraldo** [comment]
ok made the change in AWS. propagating...

**Comment by mgiraldo** [comment]
verified:
http://images.oldnyc.org/600px/708760f-a.jpg
https://images.oldnyc.org/600px/708760f-a.jpg
http://oldnyc-assets.nypl.org/600px/708760f-a.jpg

**Comment by hadro** [comment]
Nice! Thank you all.

**Comment by danvk** [comment]
Reopening since oldnyc.org itself isn't hosted over HTTPS yet :)

Thanks for the help guys!

**Comment by danvk** [comment]
oldnyc.org has been served over https for quite a while now
