### ISSUE TITLE
Provide an API

### ISSUE THREAD

**Issue by Abbe98** [danvk/oldnyc#99]
With support for bounding box requests outputting at least JSON and GeoJSON.

**Comment by danvk** [comment]
You can download JSON of the entire database. That's all the api you could
ever want!

**Comment by danvk** [comment]
In case you're curious, that file is here: https://github.com/oldnyc/oldnyc.github.io/blob/master/data.json

I'd love to see people using the data. Did you have anything in particular in mind?
